CREATE TABLESPACE lob_tablespace
    DATAFILE 'lob_datafile.dbf' SIZE 100M
    AUTOEXTEND ON NEXT 10M
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


CREATE OR REPLACE DIRECTORY LOB_DOCUMENTS_DIR AS 'C:/BLOB';

CREATE USER lob_user IDENTIFIED BY pass1234;

GRANT CONNECT TO lob_user;
GRANT RESOURCE TO lob_user;
GRANT CREATE SESSION TO lob_user;
GRANT EXECUTE ON DBMS_LOB TO lob_user;
GRANT UNLIMITED TABLESPACE TO lob_user;
GRANT READ, WRITE ON DIRECTORY LOB_DOCUMENTS_DIR TO lob_user;

ALTER USER lob_user QUOTA UNLIMITED ON lob_tablespace;


CREATE TABLE BLOB_TABLE
(
    ID   INT PRIMARY KEY,
    FOTO BLOB DEFAULT EMPTY_BLOB(),
    DOC  BFILE
);

INSERT INTO BLOB_TABLE (id, foto, doc)
        VALUES (1, BFILENAME('LOB_DOCUMENTS_DIR', 'cat2.jpg'), BFILENAME('LOB_DOCUMENTS_DIR', 'doc.docx'));

COMMIT;