LOAD DATA CHARACTERSET UTF8
INFILE authors.txt
INTO TABLE AUTHOR_COPY
REPLACE
FIELDS TERMINATED BY ','
(
  ID,
  FIRST_NAME CHAR(100) "UPPER(:FIRST_NAME)",
  LAST_NAME CHAR(100) "UPPER(:LAST_NAME)",
  PATRONYMIC CHAR(100) "UPPER(:PATRONYMIC)",
  COUNTRY CHAR(100) "UPPER(:COUNTRY)"
)