INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES (N'Джоан', N'Роулинг', N'Кэтлин', N'Великобритания');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES (N'Федор', N'Достоевский', N'Михайлович', N'Россия');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES (N'Эрнест', N'Хемингуэй', N'Миллер', N'США');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES (N'Лев', N'Толстой', N'Николаевич', N'Россия');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES (N'Джордж', N'Оруэлл', N' ', N'Великобритания');

INSERT INTO GENRE (NAME, AGE_RATING) VALUES (N'Фантастика', N'12+');
INSERT INTO GENRE (NAME, AGE_RATING) VALUES (N'Роман', N'16+');
INSERT INTO GENRE (NAME, AGE_RATING) VALUES (N'Детектив', N'16+');
INSERT INTO GENRE (NAME, AGE_RATING) VALUES (N'Приключения', N'12+');
INSERT INTO GENRE (NAME, AGE_RATING) VALUES (N'Фэнтези', N'12+');

INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES (N'Гарри Поттер и философский камень', 1, 1997, 1);
INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES (N'Преступление и наказание', 2, 1866, 2);
INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES (N'Старик и море', 3, 1952, 4);
INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES (N'Война и мир', 4, 1869, 2);
INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES (N'1984', 5, 1949, 1);

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES (N'Иван', N'Иванов', N'Иванович', '123-456-7890', 'ivan@example.com', N'Физическое лицо');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES (N'Петр', N'Петров', N'Петрович', '987-654-3210', 'petr@example.com', N'Физическое лицо');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES (N'Анна', N'Иванова', N'Петровна', '111-222-3333', 'anna@example.com', N'Юридическое лицо');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES (N'Елена', N'Смирнова', N'Ивановна', '444-555-6666', 'elena@example.com', N'Физическое лицо');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES (N'Сергей', N'Козлов', N'Александрович', '777-888-9999', 'sergey@example.com', N'Юридическое лицо');

INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES (N'Мягкая', N'Офсетная', N'Клеевое переплетение', 300, N'A5');
INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES (N'Твердая', N'Мелованная', N'Пружинный переплет', 400, N'B5');
INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES (N'Мягкая', N'Офсетная', N'Скрепление на клею', 250, N'A4');
INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES (N'Твердая', N'Мелованная', N'Твердый переплет', 500, N'A4');
INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES (N'Мягкая', N'Офсетная', N'Клеевое переплетение', 350, N'B6');

INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (1, 1, 1, '2024-02-19', 100, 1500.00, N'Создан');
INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (2, 2, 2, '2024-02-20', 200, 2500.00, N'В работе');
INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (3, 3, 3, '2024-02-21', 150, 1800.00, N'Создан');
INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (4, 4, 4, '2024-02-22', 300, 3500.00, N'Готов');
INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (5, 5, 5, '2024-02-23', 250, 2800.00, N'В работе');


