INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES ('Джоан', 'Роулинг', 'Кэтлин', 'Великобритания');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES ('Федор', 'Достоевский', 'Михайлович', 'Россия');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES ('Эрнест', 'Хемингуэй', 'Миллер', 'США');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES ('Лев', 'Толстой', 'Николаевич', 'Россия');
INSERT INTO AUTHOR (FIRST_NAME, LAST_NAME, PATRONYMIC, COUNTRY) VALUES ('Джордж', 'Оруэлл', ' ', 'Великобритания');


INSERT INTO GENRE (NAME, AGE_RATING) VALUES ('Фантастика', '12+');
INSERT INTO GENRE (NAME, AGE_RATING) VALUES ('Роман', '16+');
INSERT INTO GENRE (NAME, AGE_RATING) VALUES ('Детектив', '16+');
INSERT INTO GENRE (NAME, AGE_RATING) VALUES ('Приключения', '12+');
INSERT INTO GENRE (NAME, AGE_RATING) VALUES ('Фэнтези', '12+');

INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES ('Гарри Поттер и философский камень', 1, 1997, 1);
INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES ('Преступление и наказание', 2, 1866, 2);
INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES ('Старик и море', 3, 1952, 4);
INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES ('Война и мир', 4, 1869, 2);
INSERT INTO BOOK (NAME, AUTHOR_ID, YEAR_OF_PUBLISHING, GENRE_ID) VALUES ('1984', 4, 1949, 1);

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES ('Иван', 'Иванов', 'Иванович', '123-456-7890', 'ivan@example.com', 'Физическое лицо');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES ('Петр', 'Петров', 'Петрович', '987-654-3210', 'petr@example.com', 'Физическое лицо');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES ('Анна', 'Иванова', 'Петровна', '111-222-3333', 'anna@example.com', 'Юридическое лицо');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES ('Елена', 'Смирнова', 'Ивановна', '444-555-6666', 'elena@example.com', 'Физическое лицо');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PATRONYMIC, PHONE_NUMBER, EMAIL, TYPE) VALUES ('Сергей', 'Козлов', 'Александрович', '777-888-9999', 'sergey@example.com', 'Юридическое лицо');

INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES ('Мягкая', 'Офсетная', 'Клеевое переплетение', 300, 'A5');
INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES ('Твердая', 'Мелованная', 'Пружинный переплет', 400, 'B5');
INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES ('Мягкая', 'Офсетная', 'Скрепление на клею', 250, 'A4');
INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES ('Твердая', 'Мелованная', 'Твердый переплет', 500, 'A4');
INSERT INTO BOOK_CHARACTERISTICS (COVER_TYPE, PAPER_TYPE, BINDING_TYPE, NUMBER_OF_PAGES, PAPER_SIZE)
VALUES ('Мягкая', 'Офсетная', 'Клеевое переплетение', 350, 'B6');


INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (1, 1, 1, TO_DATE('2024-02-19', 'YYYY-MM-DD'), 100, 1500.00, 'Создан');
INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (2, 2, 2, TO_DATE('2024-02-20', 'YYYY-MM-DD'), 200, 2500.00, 'В работе');
INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (3, 3, 3, TO_DATE('2024-02-21', 'YYYY-MM-DD'), 150, 1800.00, 'Создан');
INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (4, 4, 4, TO_DATE('2024-02-22', 'YYYY-MM-DD'), 300, 3500.00, 'Готов');
INSERT INTO BOOK_ORDER (BOOK_ID, CUSTOMER_ID, BOOK_CHARACTERISTICS_ID, DATE_OF_ORDER, EDITION, TOTAL_PRICE, STATUS)
VALUES (6, 5, 5, TO_DATE('2024-02-23', 'YYYY-MM-DD'), 250, 2800.00, 'В работе');
