CREATE TABLE AUTHOR (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    FIRST_NAME NVARCHAR2(50),
    LAST_NAME NVARCHAR2(50),
    PATRONYMIC NVARCHAR2(50),
    COUNTRY NVARCHAR2(50)
);

CREATE TABLE GENRE (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME NVARCHAR2(50),
    AGE_RATING NVARCHAR2(10)
);

CREATE TABLE BOOK (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME NVARCHAR2(100),
    AUTHOR_ID INT,
    YEAR_OF_PUBLISHING INT,
    GENRE_ID INT,
    CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
    CONSTRAINT FK_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID)
);

CREATE TABLE CUSTOMER (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    FIRST_NAME NVARCHAR2(70),
    LAST_NAME NVARCHAR2(70),
    PATRONYMIC NVARCHAR2(70),
    PHONE_NUMBER VARCHAR2(20),
    EMAIL VARCHAR2(70),
    TYPE NVARCHAR2(20) CHECK (TYPE IN (N'Юридическое лицо', N'Физическое лицо'))
);

CREATE TABLE BOOK_CHARACTERISTICS (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    COVER_TYPE NVARCHAR2(50),
    PAPER_TYPE NVARCHAR2(50),
    BINDING_TYPE NVARCHAR2(50),
    NUMBER_OF_PAGES INT,
    PAPER_SIZE NVARCHAR2(50)
);

CREATE TABLE BOOK_ORDER (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    BOOK_ID INT,
    CUSTOMER_ID INT,
    BOOK_CHARACTERISTICS_ID INT,
    DATE_OF_ORDER DATE,
    EDITION INT,
    TOTAL_PRICE DECIMAL(10, 2),
    STATUS VARCHAR2(20) CHECK (STATUS IN (N'Создан', N'В работе', N'Готов')),
    CONSTRAINT FK_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    CONSTRAINT FK_BOOK_CHARACTERISTICS_ID FOREIGN KEY (BOOK_CHARACTERISTICS_ID) REFERENCES BOOK_CHARACTERISTICS(ID)
);
