CREATE TABLE AUTHOR (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    FIRST_NAME NVARCHAR2(50) NOT NULL,
    LAST_NAME NVARCHAR2(50) NOT NULL,
    PATRONYMIC NVARCHAR2(50) NOT NULL,
    COUNTRY NVARCHAR2(50) NOT NULL
);

CREATE TABLE GENRE (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME NVARCHAR2(50) NOT NULL,
    AGE_RATING NVARCHAR2(10) NOT NULL
);

CREATE TABLE BOOK (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME NVARCHAR2(100) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    YEAR_OF_PUBLISHING INT NOT NULL,
    GENRE_ID INT NOT NULL,
    CONSTRAINT FK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
    CONSTRAINT FK_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID)
);

CREATE TABLE CUSTOMER (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    FIRST_NAME NVARCHAR2(70) NOT NULL,
    LAST_NAME NVARCHAR2(70) NOT NULL,
    PATRONYMIC NVARCHAR2(70) NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(70) NOT NULL,
    TYPE NVARCHAR2(20) CHECK (TYPE IN (N'Юридическое лицо', N'Физическое лицо'))
);

CREATE TABLE BOOK_CHARACTERISTICS (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    COVER_TYPE NVARCHAR2(50) NOT NULL,
    PAPER_TYPE NVARCHAR2(50) NOT NULL,
    BINDING_TYPE NVARCHAR2(50) NOT NULL,
    NUMBER_OF_PAGES INT NOT NULL,
    PAPER_SIZE NVARCHAR2(50) NOT NULL
);

CREATE TABLE BOOK_ORDER (
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    BOOK_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    BOOK_CHARACTERISTICS_ID INT NOT NULL,
    DATE_OF_ORDER DATE NOT NULL,
    EDITION INT NOT NULL,
    TOTAL_PRICE DECIMAL(10, 2) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL CHECK (STATUS IN (N'Создан', N'В работе', N'Готов')),
    CONSTRAINT FK_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    CONSTRAINT FK_BOOK_CHARACTERISTICS_ID FOREIGN KEY (BOOK_CHARACTERISTICS_ID) REFERENCES BOOK_CHARACTERISTICS(ID)
);
