CREATE VIEW BOOK_DETAILS AS
SELECT b.ID,
       b.NAME AS BOOK_NAME,
       a.FIRST_NAME,
       a.LAST_NAME,
       a.PATRONYMIC,
       g.NAME AS GENRE_NAME,
       g.AGE_RATING
FROM BOOK b
         INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.ID
         INNER JOIN GENRE g ON b.GENRE_ID = g.ID;

CREATE VIEW CUSTOMER_ORDER_SUMMARY AS
SELECT c.ID,
       c.FIRST_NAME,
       c.LAST_NAME,
       c.PATRONYMIC,
       COUNT(o.ID)        AS TOTAL_ORDERS,
       SUM(o.TOTAL_PRICE) AS TOTAL_PRICE
FROM CUSTOMER c
         LEFT JOIN BOOK_ORDER o ON c.ID = o.CUSTOMER_ID
GROUP BY c.ID, c.FIRST_NAME, c.LAST_NAME, c.PATRONYMIC;

CREATE VIEW ORDER_DETAILS AS
SELECT o.ID , b.NAME AS BOOK_NAME,
       a.FIRST_NAME,
       a.LAST_NAME,
       a.PATRONYMIC,
       g.NAME AS GENRE,
       bc.COVER_TYPE, bc.PAPER_TYPE,
       bc.BINDING_TYPE, bc.NUMBER_OF_PAGES,
       bc.PAPER_SIZE,
       o.DATE_OF_ORDER, o.EDITION,
       o.TOTAL_PRICE, o.STATUS
FROM BOOK_ORDER o
INNER JOIN BOOK b ON o.BOOK_ID = b.ID
INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.ID
INNER JOIN GENRE g ON b.GENRE_ID = g.ID
INNER JOIN BOOK_CHARACTERISTICS bc ON o.BOOK_CHARACTERISTICS_ID = bc.ID;

